name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: 14-alpine3.1
    steps:
      - name: log node version
        run: node -v
      - name: step with docker 
        uses: docker://node:18-alpine3.15
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version 
        uses: docker://node:18-alpine3.15
        with:
          entrypoint: user/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.15

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
          