name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.15
    steps:
      - name: log node version
        run: node -v
      - name: step with docker 
        uses: docker://node:16-alpine3.15
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version 
        uses: docker://node:16-alpine3.15
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v3
      - name: Run a Script 
        uses: docker://node:16-alpine3.15
        with:
          entrypoint: ./script.sh
          args: "Some String"
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.15

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
          