name: Shell Commands

on: [push]

jobs:
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash
        run: pwd
        shell: bash
         
   
  run-shell-command:
    runs-on: ubuntu-latest
    #timeout-minutes: 360
    steps:
      - name: echo a string
        run: echo "Hello World"
        #timeout-minutes: 30
        #continue-on-error: true #to continue in case any step fail.
      - name: multiline script
        #if: failure() -to continue the jobs if step fail.
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print
          (platform.processor())
        shell: python

